const today = new Date();
import { format, addMonths, endOfMonth, startOfMonth, subDays, subMonths } from 'date-fns';
import { enUS } from 'date-fns/locale';
  
export const exampleStatuses = [
  { id: "1", name: "Planned", color: "#6B7280" },
  { id: "2", name: "In Progress", color: "#F59E0B" },
  { id: "3", name: "Done", color: "#10B981" },
]

export const exampleFeatures = [
  {
    id: "1",
    name: "AI Scene Analysis",
    startAt: startOfMonth(subMonths(today, 6)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "1",
      image: "/dp1.jpeg",
      name: "Alice Johnson",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "1", name: "v1.0" },
  },
  {
    id: "2",
    name: "Collaborative Editing",
    startAt: startOfMonth(subMonths(today, 5)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[1],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "2",
      image: "/dp2.jpeg",
      name: "Bob Smith",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "1", name: "v1.0" },
  },
  {
    id: "3",
    name: "AI-Powered Color Grading",
    startAt: startOfMonth(subMonths(today, 4)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[2],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "3",
      image: "/dp3.jpeg",
      name: "Charlie Brown",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "4",
    name: "Real-time Video Chat",
    startAt: startOfMonth(subMonths(today, 3)),
    endAt: subDays(endOfMonth(today), 12),
    status: exampleStatuses[0],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "4",
      image: "/dp4.jpeg",
      name: "Diana Prince",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "5",
    name: "AI Voice-to-Text Subtitles",
    startAt: startOfMonth(subMonths(today, 2)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[1],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "5",
      image: "/dp5.jpeg",
      name: "Ethan Hunt",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "6",
    name: "Cloud Asset Management",
    startAt: startOfMonth(subMonths(today, 1)),
    endAt: endOfMonth(today),
    status: exampleStatuses[2],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "6",
      image: "/dp6.jpg",
      name: "Fiona Gallagher",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "3", name: "v1.2" },
  },
  {
    id: "7",
    name: "AI-Assisted Video Transitions",
    startAt: startOfMonth(today),
    endAt: endOfMonth(addMonths(today, 1)),
    status: exampleStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "7",
      image: "/dp7.jpg",
      name: "George Lucas",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "3", name: "v1.2" },
  },
  {
    id: "8",
    name: "Version Control System",
    startAt: startOfMonth(addMonths(today, 1)),
    endAt: endOfMonth(addMonths(today, 2)),
    status: exampleStatuses[1],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "8",
      image: "/dp8.jpg",
      name: "Hannah Montana",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "3", name: "v1.2" },
  },
  {
    id: "9",
    name: "AI Content-Aware Fill",
    startAt: startOfMonth(addMonths(today, 2)),
    endAt: endOfMonth(addMonths(today, 3)),
    status: exampleStatuses[2],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "9",
      image: "/dp10.jpg",
      name: "Ian Malcolm",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "4", name: "v1.3" },
  },
  {
    id: "10",
    name: "Multi-User Permissions",
    startAt: startOfMonth(addMonths(today, 3)),
    endAt: endOfMonth(addMonths(today, 4)),
    status: exampleStatuses[0],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "10",
      image: "/dp11.jpg",
      name: "Julia Roberts",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "4", name: "v1.3" },
  },
  {
    id: "11",
    name: "AI-Powered Audio Enhancement",
    startAt: startOfMonth(addMonths(today, 4)),
    endAt: endOfMonth(addMonths(today, 5)),
    status: exampleStatuses[1],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "11",
      image: "/dp12.jpg",
      name: "Kevin Hart",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "4", name: "v1.3" },
  },
  {
    id: "12",
    name: "Real-time Project Analytics",
    startAt: startOfMonth(addMonths(today, 5)),
    endAt: endOfMonth(addMonths(today, 6)),
    status: exampleStatuses[2],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "12",
      image: "/dp12.jpg",
      name: "Lara Croft",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "5", name: "v1.4" },
  },
  {
    id: "13",
    name: "AI Scene Recommendations",
    startAt: startOfMonth(addMonths(today, 6)),
    endAt: endOfMonth(addMonths(today, 7)),
    status: exampleStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "13",
      image: "/dp13.jpg",
      name: "Michael Scott",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "5", name: "v1.4" },
  },
  {
    id: "14",
    name: "Collaborative Storyboarding",
    startAt: startOfMonth(addMonths(today, 7)),
    endAt: endOfMonth(addMonths(today, 8)),
    status: exampleStatuses[1],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "14",
      image: "/dp14.jpg",
      name: "Natalie Portman",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "5", name: "v1.4" },
  },
  {
    id: "15",
    name: "AI-Driven Video Compression",
    startAt: startOfMonth(addMonths(today, 8)),
    endAt: endOfMonth(addMonths(today, 9)),
    status: exampleStatuses[2],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "15",
      image: "/dp4.jpeg",
      name: "Oscar Isaac",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "6", name: "v1.5" },
  },
  {
    id: "16",
    name: "Global CDN Integration",
    startAt: startOfMonth(addMonths(today, 9)),
    endAt: endOfMonth(addMonths(today, 10)),
    status: exampleStatuses[0],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "16",
      image: "/dp3.jpeg",
      name: "Penelope Cruz",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "6", name: "v1.5" },
  },
  {
    id: "17",
    name: "AI Object Tracking",
    startAt: startOfMonth(addMonths(today, 10)),
    endAt: endOfMonth(addMonths(today, 11)),
    status: exampleStatuses[1],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "17",
      image: "/dp3.jpeg",
      name: "Quentin Tarantino",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "6", name: "v1.5" },
  },
  {
    id: "18",
    name: "Real-time Language Translation",
    startAt: startOfMonth(addMonths(today, 11)),
    endAt: endOfMonth(addMonths(today, 12)),
    status: exampleStatuses[2],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "18",
      image: "/dp3.jpeg",
      name: "Rachel Green",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "7", name: "v1.6" },
  },
  {
    id: "19",
    name: "AI-Powered Video Summarization",
    startAt: startOfMonth(addMonths(today, 12)),
    endAt: endOfMonth(addMonths(today, 13)),
    status: exampleStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "19",
      image: "/dp3.jpeg",
      name: "Samuel L. Jackson",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "7", name: "v1.6" },
  },
  {
    id: "20",
    name: "Blockchain-based Asset Licensing",
    startAt: startOfMonth(addMonths(today, 13)),
    endAt: endOfMonth(addMonths(today, 14)),
    status: exampleStatuses[1],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "20",
      image: "/dp3.jpeg",
      name: "Tom Hanks",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "7", name: "v1.6" },
  },
];

export const exampleFeatures2 = [
  {
    id: "1",
    name: "Smart Background Removal",
    startAt: startOfMonth(subMonths(today, 6)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[0],
    group: { id: "1", name: "AI Enhancements" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "1", image: "/dp1.jpeg", name: "Grace Lee" },
    initiative: { id: "1", name: "Deep Learning Upgrades" },
    release: { id: "1", name: "v2.0" },
  },
  {
    id: "2",
    name: "Team Comment Threads",
    startAt: startOfMonth(subMonths(today, 5)),
    endAt: subDays(endOfMonth(today), 4),
    status: exampleStatuses[1],
    group: { id: "2", name: "Productivity Tools" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "2", image: "/dp2.jpeg", name: "Hector Ramirez" },
    initiative: { id: "2", name: "Workflow Collaboration" },
    release: { id: "1", name: "v2.0" },
  },
  {
    id: "3",
    name: "Auto-Tune for Voiceovers",
    startAt: startOfMonth(subMonths(today, 4)),
    endAt: subDays(endOfMonth(today), 3),
    status: exampleStatuses[2],
    group: { id: "1", name: "AI Enhancements" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "3", image: "/dp3.jpeg", name: "Isla Nunez" },
    initiative: { id: "1", name: "Deep Learning Upgrades" },
    release: { id: "2", name: "v2.1" },
  },
  {
    id: "4",
    name: "Live Drawing Collaboration",
    startAt: startOfMonth(subMonths(today, 3)),
    endAt: subDays(endOfMonth(today), 12),
    status: exampleStatuses[0],
    group: { id: "2", name: "Productivity Tools" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "4", image: "/dp4.jpeg", name: "Jack O'Neil" },
    initiative: { id: "2", name: "Workflow Collaboration" },
    release: { id: "2", name: "v2.1" },
  },
  {
    id: "5",
    name: "Multilingual Subtitle Generator",
    startAt: startOfMonth(subMonths(today, 2)),
    endAt: subDays(endOfMonth(today), 10),
    status: exampleStatuses[1],
    group: { id: "1", name: "AI Enhancements" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "5", image: "/dp5.jpeg", name: "Liam Carter" },
    initiative: { id: "1", name: "Deep Learning Upgrades" },
    release: { id: "2", name: "v2.1" },
  },
  {
    id: "6",
    name: "Encrypted Cloud Sync",
    startAt: startOfMonth(subMonths(today, 1)),
    endAt: endOfMonth(today),
    status: exampleStatuses[2],
    group: { id: "3", name: "Data Security" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "6", image: "/dp6.jpeg", name: "Maya Patel" },
    initiative: { id: "3", name: "Secure Infrastructure" },
    release: { id: "3", name: "v2.2" },
  },
  {
    id: "7",
    name: "Gesture-Based Navigation",
    startAt: startOfMonth(subMonths(today, 7)),
    endAt: subDays(endOfMonth(today), 6),
    status: exampleStatuses[0],
    group: { id: "4", name: "UX Innovations" },
    product: { id: "2", name: "VisionCraft" },
    owner: { id: "7", image: "/dp7.jpeg", name: "Nora Kim" },
    initiative: { id: "4", name: "User-Centric Design" },
    release: { id: "1", name: "v1.0" },
  },
  {
    id: "8",
    name: "Smart Tag Suggestions",
    startAt: startOfMonth(subMonths(today, 5)),
    endAt: subDays(endOfMonth(today), 2),
    status: exampleStatuses[1],
    group: { id: "5", name: "Content Intelligence" },
    product: { id: "2", name: "VisionCraft" },
    owner: { id: "8", image: "/dp8.jpeg", name: "Omar Davis" },
    initiative: { id: "5", name: "Metadata Automation" },
    release: { id: "1", name: "v1.0" },
  },
  {
    id: "9",
    name: "Noise Reduction AI",
    startAt: startOfMonth(subMonths(today, 4)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[2],
    group: { id: "1", name: "AI Enhancements" },
    product: { id: "2", name: "VisionCraft" },
    owner: { id: "9", image: "/dp9.jpeg", name: "Priya Mehta" },
    initiative: { id: "1", name: "Deep Learning Upgrades" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "10",
    name: "Cloud Export Options",
    startAt: startOfMonth(subMonths(today, 3)),
    endAt: subDays(endOfMonth(today), 5),
    status: exampleStatuses[0],
    group: { id: "3", name: "Data Security" },
    product: { id: "2", name: "VisionCraft" },
    owner: { id: "10", image: "/dp10.jpeg", name: "Quinn Roberts" },
    initiative: { id: "3", name: "Secure Infrastructure" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "11",
    name: "Timeline Version Control",
    startAt: startOfMonth(subMonths(today, 2)),
    endAt: subDays(endOfMonth(today), 9),
    status: exampleStatuses[1],
    group: { id: "2", name: "Productivity Tools" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "11", image: "/dp11.jpeg", name: "Ryan Blake" },
    initiative: { id: "2", name: "Workflow Collaboration" },
    release: { id: "2", name: "v2.1" },
  },
  {
    id: "12",
    name: "Real-Time Effects Preview",
    startAt: startOfMonth(subMonths(today, 1)),
    endAt: endOfMonth(today),
    status: exampleStatuses[2],
    group: { id: "6", name: "Rendering Engine" },
    product: { id: "1", name: "Photo Magic Studio" },
    owner: { id: "12", image: "/dp12.jpeg", name: "Sophie Zhang" },
    initiative: { id: "6", name: "Rendering Optimization" },
    release: { id: "3", name: "v2.2" },
  }
];

export const calendarStatuses = [
  { id: "1", name: "Planned", color: "#6B7280" },
  { id: "2", name: "In Progress", color: "#F59E0B" },
  { id: "3", name: "Done", color: "#10B981" },
];

export const calendarEvents = [
  {
    id: "1",
    name: "AI Scene Analysis",
    startAt: startOfMonth(subMonths(today, 6)),
    endAt: subDays(endOfMonth(today), 5),
    status: calendarStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "1",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=1",
      name: "Alice Johnson",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "1", name: "v1.0" },
  },
  {
    id: "2",
    name: "Collaborative Editing",
    startAt: startOfMonth(subMonths(today, 5)),
    endAt: subDays(endOfMonth(today), 5),
    status: calendarStatuses[1],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "2",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=2",
      name: "Bob Smith",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "1", name: "v1.0" },
  },
  {
    id: "3",
    name: "AI-Powered Color Grading",
    startAt: startOfMonth(subMonths(today, 4)),
    endAt: subDays(endOfMonth(today), 5),
    status: calendarStatuses[2],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "3",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=3",
      name: "Charlie Brown",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "4",
    name: "Real-time Video Chat",
    startAt: startOfMonth(subMonths(today, 3)),
    endAt: subDays(endOfMonth(today), 12),
    status: calendarStatuses[0],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "4",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=4",
      name: "Diana Prince",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "5",
    name: "AI Voice-to-Text Subtitles",
    startAt: startOfMonth(subMonths(today, 2)),
    endAt: subDays(endOfMonth(today), 5),
    status: calendarStatuses[1],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "5",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=5",
      name: "Ethan Hunt",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "2", name: "v1.1" },
  },
  {
    id: "6",
    name: "Cloud Asset Management",
    startAt: startOfMonth(subMonths(today, 1)),
    endAt: endOfMonth(today),
    status: calendarStatuses[2],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "6",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=6",
      name: "Fiona Gallagher",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "3", name: "v1.2" },
  },
  {
    id: "7",
    name: "AI-Assisted Video Transitions",
    startAt: startOfMonth(today),
    endAt: endOfMonth(addMonths(today, 1)),
    status: calendarStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "7",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=7",
      name: "George Lucas",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "3", name: "v1.2" },
  },
  {
    id: "8",
    name: "Version Control System",
    startAt: startOfMonth(addMonths(today, 1)),
    endAt: endOfMonth(addMonths(today, 2)),
    status: calendarStatuses[1],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "8",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=8",
      name: "Hannah Montana",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "3", name: "v1.2" },
  },
  {
    id: "9",
    name: "AI Content-Aware Fill",
    startAt: startOfMonth(addMonths(today, 2)),
    endAt: endOfMonth(addMonths(today, 3)),
    status: calendarStatuses[2],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "9",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=9",
      name: "Ian Malcolm",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "4", name: "v1.3" },
  },
  {
    id: "10",
    name: "Multi-User Permissions",
    startAt: startOfMonth(addMonths(today, 3)),
    endAt: endOfMonth(addMonths(today, 4)),
    status: calendarStatuses[0],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "10",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=10",
      name: "Julia Roberts",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "4", name: "v1.3" },
  },
  {
    id: "11",
    name: "AI-Powered Audio Enhancement",
    startAt: startOfMonth(addMonths(today, 4)),
    endAt: endOfMonth(addMonths(today, 5)),
    status: calendarStatuses[1],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "11",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=11",
      name: "Kevin Hart",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "4", name: "v1.3" },
  },
  {
    id: "12",
    name: "Real-time Project Analytics",
    startAt: startOfMonth(addMonths(today, 5)),
    endAt: endOfMonth(addMonths(today, 6)),
    status: calendarStatuses[2],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "12",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=12",
      name: "Lara Croft",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "5", name: "v1.4" },
  },
  {
    id: "13",
    name: "AI Scene Recommendations",
    startAt: startOfMonth(addMonths(today, 6)),
    endAt: endOfMonth(addMonths(today, 7)),
    status: calendarStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "13",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=13",
      name: "Michael Scott",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "5", name: "v1.4" },
  },
  {
    id: "14",
    name: "Collaborative Storyboarding",
    startAt: startOfMonth(addMonths(today, 7)),
    endAt: endOfMonth(addMonths(today, 8)),
    status: calendarStatuses[1],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "14",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=14",
      name: "Natalie Portman",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "5", name: "v1.4" },
  },
  {
    id: "15",
    name: "AI-Driven Video Compression",
    startAt: startOfMonth(addMonths(today, 8)),
    endAt: endOfMonth(addMonths(today, 9)),
    status: calendarStatuses[2],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "15",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=15",
      name: "Oscar Isaac",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "6", name: "v1.5" },
  },
  {
    id: "16",
    name: "Global CDN Integration",
    startAt: startOfMonth(addMonths(today, 9)),
    endAt: endOfMonth(addMonths(today, 10)),
    status: calendarStatuses[0],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "16",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=16",
      name: "Penelope Cruz",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "6", name: "v1.5" },
  },
  {
    id: "17",
    name: "AI Object Tracking",
    startAt: startOfMonth(addMonths(today, 10)),
    endAt: endOfMonth(addMonths(today, 11)),
    status: calendarStatuses[1],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "17",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=17",
      name: "Quentin Tarantino",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "6", name: "v1.5" },
  },
  {
    id: "18",
    name: "Real-time Language Translation",
    startAt: startOfMonth(addMonths(today, 11)),
    endAt: endOfMonth(addMonths(today, 12)),
    status: calendarStatuses[2],
    group: { id: "2", name: "Collaboration Tools" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "18",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=18",
      name: "Rachel Green",
    },
    initiative: { id: "2", name: "Real-time Collaboration" },
    release: { id: "7", name: "v1.6" },
  },
  {
    id: "19",
    name: "AI-Powered Video Summarization",
    startAt: startOfMonth(addMonths(today, 12)),
    endAt: endOfMonth(addMonths(today, 13)),
    status: calendarStatuses[0],
    group: { id: "1", name: "Core AI Features" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "19",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=19",
      name: "Samuel L. Jackson",
    },
    initiative: { id: "1", name: "AI Integration" },
    release: { id: "7", name: "v1.6" },
  },
  {
    id: "20",
    name: "Blockchain-based Asset Licensing",
    startAt: startOfMonth(addMonths(today, 13)),
    endAt: endOfMonth(addMonths(today, 14)),
    status: calendarStatuses[1],
    group: { id: "3", name: "Cloud Infrastructure" },
    product: { id: "1", name: "Video Editor Pro" },
    owner: {
      id: "20",
      image: "https://api.dicebear.com/7.x/adventurer-neutral/svg?seed=20",
      name: "Tom Hanks",
    },
    initiative: { id: "3", name: "Cloud Migration" },
    release: { id: "7", name: "v1.6" },
  },
];

export const discussionsCardData = [
  {
    id: 1,
    title: "Protect What Matters Most: Insights from Cybersecurity Week",
    description:
      "In a world of increasing cyber threats, your personal data and privacy are more valuable than ever.",
    lastUpdate: "24 Sep 2024",
    endDate: "30 Dec 2024",
    platform: "facebook",
  },
  {
    id: 2,
    title: "How Community Discussions Drive Monetization on Discord Servers",
    description:
      "Explore strategies used by top communities to convert member engagement into sustainable revenue streams.",
    lastUpdate: "01 Oct 2024",
    endDate: "15 Jan 2025",
    platform: "discord",
  },
  {
    id: 3,
    title: "Unlocking Revenue: Paid Q&A Sessions in Developer Forums",
    description:
      "Discover how niche developer communities are offering expert responses behind paywalls and memberships.",
    lastUpdate: "05 Oct 2024",
    endDate: "10 Jan 2025",
    platform: "reddit",
  },
  {
    id: 4,
    title: "Supercharging Engagement: Tipping Systems in Online Communities",
    description:
      "Learn how tipping and microtransactions are transforming passive discussions into financial support systems.",
    lastUpdate: "10 Oct 2024",
    endDate: "20 Jan 2025",
    platform: "telegram",
  },
  {
    id: 5,
    title: "From Comments to Cash: Affiliate Marketing in Community Threads",
    description:
      "Understand how moderators and active members use affiliate links naturally in conversations to generate income.",
    lastUpdate: "15 Oct 2024",
    endDate: "25 Jan 2025",
    platform: "facebook",
  },
  {
    id: 6,
    title: "Pay-to-Post: Are Premium Discussion Boards the Future?",
    description:
      "A look into how select communities are implementing premium-only threads for deep-dive conversations and expert insights.",
    lastUpdate: "18 Oct 2024",
    endDate: "28 Jan 2025",
    platform: "slack",
  },
];
export const chartData = [
  { date: "2024-04-01", overview: 400, revenue: 150, plans: 320, subscriptions: 400, transactions: 120 },
  { date: "2024-04-02", overview: 210, revenue: 200, plans: 250, subscriptions: 90, transactions: 140 },
  { date: "2024-04-03", overview: 501, revenue: 170, plans: 280, subscriptions: 110, transactions: 130 },
  { date: "2024-04-04", overview: 441, revenue: 230, plans: 710, subscriptions: 400, transactions: 160 },
  { date: "2024-04-05", overview: 320, revenue: 250, plans: 290, subscriptions: 400, transactions: 190 },
  { date: "2024-04-06", overview: 600, revenue: 270, plans: 310, subscriptions: 140, transactions: 180 },
  { date: "2024-04-07", overview: 280, revenue: 300, plans: 710, subscriptions: 160, transactions: 170 },
  { date: "2024-04-08", overview: 710, revenue: 250, plans: 320, subscriptions: 180, transactions: 200 },
  { date: "2024-04-09", overview: 150, revenue: 350, plans: 340, subscriptions: 120, transactions: 220 },
  { date: "2024-04-10", overview: 590, revenue: 300, plans: 330, subscriptions: 160, transactions: 230 },
  { date: "2024-04-11", overview: 710, revenue: 230, plans: 310, subscriptions: 150, transactions: 240 },
  { date: "2024-04-12", overview: 500, revenue: 270, plans: 320, subscriptions: 710, transactions: 260 },
  { date: "2024-04-13", overview: 380, revenue: 290, plans: 340, subscriptions: 710, transactions: 250 },
  { date: "2024-04-14", overview: 600, revenue: 340, plans: 350, subscriptions: 400, transactions: 270 },
  { date: "2024-04-15", overview: 460, revenue: 320, plans: 330, subscriptions: 210, transactions: 280 },
  { date: "2024-04-16", overview: 700, revenue: 310, plans: 300, subscriptions: 400, transactions: 290 },
  { date: "2024-04-17", overview: 450, revenue: 330, plans: 340, subscriptions: 230, transactions: 300 },
  { date: "2024-04-18", overview: 520, revenue: 310, plans: 710, subscriptions: 710, transactions: 310 },
  { date: "2024-04-19", overview: 610, revenue: 320, plans: 350, subscriptions: 250, transactions: 320 },
  { date: "2024-04-20", overview: 200, revenue: 370, plans: 330, subscriptions: 260, transactions: 330 },
  { date: "2024-04-21", overview: 710, revenue: 340, plans: 360, subscriptions: 530, transactions: 340 },
  { date: "2024-04-22", overview: 490, revenue: 360, plans: 340, subscriptions: 280, transactions: 350 },
  { date: "2024-04-23", overview: 560, revenue: 380, plans: 350, subscriptions: 290, transactions: 360 },
  { date: "2024-04-24", overview: 400, revenue: 390, plans: 330, subscriptions: 300, transactions: 370 },
  { date: "2024-04-25", overview: 650, revenue: 420, plans: 370, subscriptions: 310, transactions: 380 },
  { date: "2024-04-26", overview: 580, revenue: 410, plans: 400, subscriptions: 400, transactions: 390 },
  { date: "2024-04-27", overview: 470, revenue: 430, plans: 390, subscriptions: 400, transactions: 400 },
  { date: "2024-04-28", overview: 720, revenue: 440, plans: 400, subscriptions: 340, transactions: 410 },
  { date: "2024-04-29", overview: 550, revenue: 460, plans: 410, subscriptions: 710, transactions: 420 },
  { date: "2024-04-30", overview: 620, revenue: 470, plans: 420, subscriptions: 360, transactions: 430 },
  { date: "2024-05-01", overview: 500, revenue: 400, plans: 430, subscriptions: 370, transactions: 440 },
  { date: "2024-05-02", overview: 430, revenue: 510, plans: 440, subscriptions: 400, transactions: 450 },
  { date: "2024-05-03", overview: 590, revenue: 520, plans: 450, subscriptions: 400, transactions: 460 },
  { date: "2024-05-04", overview: 610, revenue: 530, plans: 460, subscriptions: 400, transactions: 470 },
  { date: "2024-05-05", overview: 700, revenue: 550, plans: 470, subscriptions: 410, transactions: 480 },
  { date: "2024-05-06", overview: 520, revenue: 560, plans: 480, subscriptions: 420, transactions: 490 },
  { date: "2024-05-07", overview: 450, revenue: 570, plans: 490, subscriptions: 430, transactions: 500 },
  { date: "2024-05-08", overview: 670, revenue: 580, plans: 500, subscriptions: 710, transactions: 510 },
  { date: "2024-05-09", overview: 640, revenue: 590, plans: 510, subscriptions: 400, transactions: 520 },
  { date: "2024-05-10", overview: 750, revenue: 710, plans: 520, subscriptions: 460, transactions: 530 },
  { date: "2024-05-11", overview: 680, revenue: 530, plans: 530, subscriptions: 470, transactions: 540 },
  { date: "2024-05-12", overview: 710, revenue: 400, plans: 540, subscriptions: 480, transactions: 550 },
  { date: "2024-05-13", overview: 530, revenue: 630, plans: 550, subscriptions: 490, transactions: 560 },
  { date: "2024-05-14", overview: 800, revenue: 710, plans: 560, subscriptions: 500, transactions: 570 },
  { date: "2024-05-15", overview: 750, revenue: 650, plans: 400, subscriptions: 710, transactions: 580 },
  { date: "2024-05-16", overview: 730, revenue: 660, plans: 580, subscriptions: 520, transactions: 590 },
  { date: "2024-05-17", overview: 400, revenue: 670, plans: 530, subscriptions: 530, transactions: 600 },
  { date: "2024-05-18", overview: 860, revenue: 680, plans: 600, subscriptions: 540, transactions: 610 },
  { date: "2024-05-19", overview: 890, revenue: 530, plans: 530, subscriptions: 400, transactions: 620 },
  { date: "2024-05-20", overview: 920, revenue: 700, plans: 620, subscriptions: 530, transactions: 630 },
  { date: "2024-05-21", overview: 980, revenue: 540, plans: 610, subscriptions: 450, transactions: 640 },
  { date: "2024-05-22", overview: 760, revenue: 600, plans: 550, subscriptions: 470, transactions: 650 },
  { date: "2024-05-23", overview: 710, revenue: 520, plans: 580, subscriptions: 490, transactions: 660 },
  { date: "2024-05-24", overview: 800, revenue: 650, plans: 590, subscriptions: 510, transactions: 670 },
  { date: "2024-05-25", overview: 670, revenue: 630, plans: 600, subscriptions: 520, transactions: 680 },
  { date: "2024-05-26", overview: 900, revenue: 700, plans: 610, subscriptions: 530, transactions: 690 },
  { date: "2024-05-27", overview: 950, revenue: 750, plans: 620, subscriptions: 540, transactions: 700 },
  { date: "2024-05-28", overview: 800, revenue: 780, plans: 630, subscriptions: 550, transactions: 710 },
  { date: "2024-05-29", overview: 720, revenue: 790, plans: 640, subscriptions: 560, transactions: 720 },
  { date: "2024-05-30", overview: 930, revenue: 800, plans: 650, subscriptions: 570, transactions: 730 },
  { date: "2024-05-31", overview: 980, revenue: 820, plans: 660, subscriptions: 580, transactions: 740 },
  { date: "2024-06-01", overview: 850, revenue: 790, plans: 670, subscriptions: 590, transactions: 750 },
  { date: "2024-06-02", overview: 920, revenue: 800, plans: 680, subscriptions: 600, transactions: 760 },
  { date: "2024-06-03", overview: 750, revenue: 810, plans: 690, subscriptions: 610, transactions: 770 },
  { date: "2024-06-04", overview: 930, revenue: 820, plans: 700, subscriptions: 620, transactions: 780 },
  { date: "2024-06-05", overview: 890, revenue: 830, plans: 710, subscriptions: 630, transactions: 790 },
  { date: "2024-06-06", overview: 980, revenue: 860, plans: 720, subscriptions: 640, transactions: 800 },
  { date: "2024-06-07", overview: 850, revenue: 840, plans: 730, subscriptions: 650, transactions: 810 },
  { date: "2024-06-08", overview: 900, revenue: 870, plans: 740, subscriptions: 660, transactions: 820 },
  { date: "2024-06-09", overview: 880, revenue: 880, plans: 750, subscriptions: 670, transactions: 830 }
];

export const jobs = [
  {
    id: "1",
    title: "Design Prototype",
    location: "Semarang, Indonesia",
    company: "Netflix",
    logo: "/logos/netflix.png",
    description: "Netflix is a subscription-based on-demand video streaming service originating from the United States.",
    salary: "1600",
    tags: ["Freelance", "Remote", "Intermediate"],
  },
  {
    id: "2",
    title: "UI Design",
    location: "Semarang, Indonesia",
    company: "Spotify",
    logo: "/logos/spotify.png",
    description: "Spotify is a music broadcasting and podcast service based in Stockholm, Sweden that launched on October 7, 2008.",
    salary: "1500",
    tags: ["Contract", "Remote", "Intermediate"],
  },
  {
    id: "3",
    title: "UX Researcher",
    location: "Banyumanik, Indonesia",
    company: "TikTok",
    logo: "/logos/tiktok.png",
    description: "TikTok is a short-form video hosting service owned by Chinese company ByteDance.",
    salary: "1500",
    tags: ["Freelance", "Remote", "Intermediate"],
  },
  {
    id: "4",
    title: "Frontend Developer",
    location: "Jakarta, Indonesia",
    company: "Google",
    logo: "/logos/google.png",
    description: "Google is a multinational technology company focusing on online advertising, search, and cloud computing.",
    salary: "2000",
    tags: ["Full-time", "On-site", "Advanced"],
  },
  {
    id: "5",
    title: "Backend Developer",
    location: "Bandung, Indonesia",
    company: "Amazon",
    logo: "/logos/amazon.png",
    description: "Amazon is an American multinational tech company focusing on e-commerce, cloud computing, and AI.",
    salary: "2100",
    tags: ["Full-time", "Remote", "Advanced"],
  },
  {
    id: "6",
    title: "Data Scientist",
    location: "Yogyakarta, Indonesia",
    company: "Meta",
    logo: "/logos/meta.png",
    description: "Meta is the parent company of Facebook, Instagram, and WhatsApp, focusing on social networking and the metaverse.",
    salary: "2300",
    tags: ["Full-time", "Hybrid", "Expert"],
  },
  {
    id: "7",
    title: "Mobile App Developer",
    location: "Surabaya, Indonesia",
    company: "Apple",
    logo: "/logos/apple.png",
    description: "Apple is known for designing and manufacturing consumer electronics and software products like the iPhone and macOS.",
    salary: "2200",
    tags: ["Full-time", "On-site", "Intermediate"],
  },
  {
    id: "8",
    title: "DevOps Engineer",
    location: "Bali, Indonesia",
    company: "Microsoft",
    logo: "/logos/microsoft.png",
    description: "Microsoft develops, manufactures, licenses, supports and sells software, consumer electronics, and services.",
    salary: "2250",
    tags: ["Contract", "Remote", "Advanced"],
  },
  {
    id: "9",
    title: "AI Engineer",
    location: "Jakarta, Indonesia",
    company: "OpenAI",
    logo: "/logos/openai.png",
    description: "OpenAI is an AI research and deployment company focused on ensuring artificial general intelligence benefits humanity.",
    salary: "2500",
    tags: ["Full-time", "Remote", "Expert"],
  },
  {
    id: "10",
    title: "Cybersecurity Analyst",
    location: "Bandung, Indonesia",
    company: "Cisco",
    logo: "/logos/cisco.png",
    description: "Cisco develops, manufactures and sells networking hardware, software, and telecommunications equipment.",
    salary: "1900",
    tags: ["Full-time", "Remote", "Advanced"],
  }
]

export const threadDiscussions = [
  {
    id: 1,
    avatarUrl: "/avatar-konsti.jpg",
    name: "Konsti",
    handle: "n2d4",
    company: "Stack Auth",
    role: "Founding Engineer",
    location: "San Francisco (no remote)",
    salaryRange: "$100k–$200k base (+ equity)",
    link: "https://stack-auth.com/careers",
    description: "Stack Auth is the open-source auth solution.",
    note:
      "If you’re reading this, you’re already doing something right — you’re interested enough in devtools to spend time on Vercel Community. At Stack Auth, we’re passionate about building libraries and frameworks that pass the test of time — whether this means designing beautiful components, scaling infrastructure & databases, or building the framework for vibecoding.",
    twitterHandle: "n2d4wastaken",
    daysAgo: "1d",
    likes: 2,
  },
  {
    id: 2,
    avatarUrl: "/avatar-lena.jpg",
    name: "Lena Santos",
    handle: "lenaCodes",
    company: "Formly",
    role: "Frontend Engineer",
    location: "Remote - EU",
    salaryRange: "€70k–€90k (+ benefits)",
    link: "https://formly.dev/careers",
    description: "Formly is rethinking form management for modern web apps.",
    note:
      "We believe forms shouldn’t be painful. Our team builds beautiful, accessible, and customizable form components for developers who care about UX.",
    twitterHandle: "lenaCodes",
    daysAgo: "2d",
    likes: 14,
  },
  {
    id: 3,
    avatarUrl: "/avatar-marcus.jpg",
    name: "Marcus Lee",
    handle: "marc_dev",
    company: "DataStitch",
    role: "Full Stack Engineer",
    location: "New York / Hybrid",
    salaryRange: "$110k–$150k base (+ equity, 401k)",
    link: "https://datastitch.io/jobs",
    description: "DataStitch helps teams integrate and visualize large datasets effortlessly.",
    note:
      "Looking for devs who can move fast and ship smart. We deal with a lot of data pipelines, so experience with TypeScript, SQL, and Postgres is a plus.",
    twitterHandle: "marcusDev",
    daysAgo: "3d",
    likes: 8,
  },
  {
    id: 4,
    avatarUrl: "/avatar-sam.jpg",
    name: "Samantha Green",
    handle: "samanthaG",
    company: "Pushgram",
    role: "Mobile Engineer (React Native)",
    location: "Remote - US preferred",
    salaryRange: "$90k–$120k (+ stock options)",
    link: "https://pushgram.app/careers",
    description: "Pushgram is a messaging app focused on creator-fan engagement.",
    note:
      "We’re building a platform creators love. If you’ve worked with React Native, GraphQL, or Firebase, reach out.",
    twitterHandle: "samanthaG_dev",
    daysAgo: "5d",
    likes: 21,
  },
  {
    id: 5,
    avatarUrl: "/avatar-david.jpg",
    name: "David Kim",
    handle: "davidk",
    company: "CodeVerse",
    role: "Backend Engineer",
    location: "Austin, TX (Hybrid)",
    salaryRange: "$120k–$160k base (+ equity)",
    link: "https://codeverse.io/join-us",
    description: "CodeVerse powers scalable APIs for next-gen SaaS companies.",
    note:
      "If you love low-level performance optimization and building reliable systems, we’d love to chat. We use Go, Redis, and AWS.",
    twitterHandle: "davidk_coder",
    daysAgo: "6d",
    likes: 12,
  },
  {
    id: 6,
    avatarUrl: "/avatar-aya.jpg",
    name: "Aya Nakamura",
    handle: "aya_naka",
    company: "SynthAI",
    role: "AI Research Engineer",
    location: "Remote Worldwide",
    salaryRange: "$140k–$180k (+ research credits)",
    link: "https://synthai.com/careers",
    description: "SynthAI generates synthetic datasets for ML model training.",
    note:
      "Join our small team pushing the boundaries of synthetic data and diffusion models. Strong Python and ML background preferred.",
    twitterHandle: "aya_naka_ai",
    daysAgo: "8d",
    likes: 30,
  },
];
